In [1]:
import torch
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_capability(0))
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))
torch.cuda.set_device(0)
print(torch.cuda.current_device())

AssertionError: 
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

In [11]:
##################  Erstes handmade NN  ####################

import torch
import torch.nn as nn

n_in =10#input
n_h=5 #hidden layer size
n_out=1#output
batch_size=10#batch size
y = torch.tensor([[0.],[1.],[2.],[3.],[4.],[5.]])
x=torch.tensor([[0.],[1.],[2.],[3.],[4.],[5.]])
def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.data.fill_(1.0)
        print(m.weight)
net =nn.Sequential(nn.Linear(1,10),
                   nn.Sigmoid(),
                   nn.Linear(10, 1),
                   )
net.apply(init_weights)
            
criterion = torch.nn.MSELoss()#wie wird loss berechnet            
loss=criterion(y[1],x[0])       

epoch=0
optimizer = torch.optim.SGD(net.parameters(), lr = 0.1)


while loss.item()>0.01:
    epoch+=1
    y_pred = net(x)#model.predict --> ist das selbe in sklearn

    # loss wird anhand von criterion berechnet
    loss = criterion(y_pred, y)
    print("epoch: ",epoch,"Loss: ",loss.item())

    # Gradienten auf null setzen
    optimizer.zero_grad()

    # Backwardpass aller Gewichte und Biases anhand Backpropagation
    loss.backward()

    # Parameterupdate
    optimizer.step()
net(x[2])

Linear(in_features=1, out_features=10, bias=True)
Parameter containing:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)
Sigmoid()
Linear(in_features=10, out_features=1, bias=True)
Parameter containing:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=10, out_features=1, bias=True)
)
epoch:  1 Loss:  31.21257781982422
epoch:  2 Loss:  9.828660011291504
epoch:  3 Loss:  2.1334309577941895
epoch:  4 Loss:  0.9510778188705444
epoch:  5 Loss:  0.6984660029411316
epoch:  6 Loss:  0.6390078067779541
epoch:  7 Loss:  0.6100386381149292
epoch:  8 Loss:  0.5868361592292786
epoch:  9 Loss:  0.5651189088821411
epoch:  10 Loss:  0.5441954731941223
epoch:  11 Loss:  0.5239441990852356
epoch:  12 Loss:  0.5043361783027649
epoch:  13 Loss:  0.4853582382202148

tensor([2.0264], grad_fn=<AddBackward0>)

In [20]:
########## Convolutional neural net ############


import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
import torchvision
from torchvision import datasets,transforms
#für GPU
#device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#
train_loader = torch.utils.data.DataLoader(datasets.MNIST('./data',download=True,train=True,transform=transforms.Compose
                                                          ([transforms.ToTensor()])),batch_size=10,shuffle=True)

test_loader = torch.utils.data.DataLoader(datasets.MNIST('./data',download=True,train=False,transform=transforms.Compose
                                                         ([transforms.ToTensor()])),batch_size=10,shuffle=True)





CNN =nn.Sequential(
                   nn.Conv2d(1,32,2),
                   nn.ReLU(),
                   
                   nn.MaxPool2d(2),
                   nn.Conv2d(32,128,2),
                   nn.ReLU(),
                   
                   nn.Linear(12,48),
                   nn.ReLU(),
                   
                   nn.Linear(48,96),
                   nn.ReLU(),
    
                   nn.Linear(96,10),
                   nn.ReLU()
                   )
#CNN=CNN.to(device)
criterion = torch.nn.MSELoss()            


optimizer = torch.optim.Adam(CNN.parameters(),lr=0.25)
def train(epoch):
    
    
    for batch_id, (data, label) in enumerate(train_loader):
        print("batch_nr: ",batch_id)
        data =torch.Tensor(data)
        data=data.float()
        #data=data.to(device)
        target = torch.Tensor(label.float())
        target=target.float()
        #target=target.to(device)
        optimizer.zero_grad()

        preds = CNN(data)

        loss =criterion(preds, target)
        print("loss: ",loss.item())
        loss.backward()

        optimizer.step()
        

train(100)

batch_nr:  0
loss:  23.805728912353516
batch_nr:  1
loss:  393537.09375
batch_nr:  2
loss:  20.089189529418945
batch_nr:  3
loss:  20.46936798095703
batch_nr:  4
loss:  28.877511978149414
batch_nr:  5
loss:  23.355735778808594
batch_nr:  6
loss:  18.843534469604492
batch_nr:  7
loss:  18.572628021240234
batch_nr:  8
loss:  20.642536163330078
batch_nr:  9
loss:  21.895631790161133
batch_nr:  10
loss:  30.335912704467773
batch_nr:  11
loss:  22.171131134033203
batch_nr:  12
loss:  20.118589401245117
batch_nr:  13
loss:  25.593122482299805
batch_nr:  14
loss:  14.468789100646973
batch_nr:  15
loss:  13.650882720947266
batch_nr:  16
loss:  27.748071670532227
batch_nr:  17
loss:  15.77002239227295
batch_nr:  18
loss:  18.963348388671875
batch_nr:  19
loss:  14.75402545928955
batch_nr:  20
loss:  18.622663497924805
batch_nr:  21
loss:  28.25505256652832
batch_nr:  22
loss:  20.581689834594727
batch_nr:  23
loss:  12.7889404296875
batch_nr:  24
loss:  29.435531616210938
batch_nr:  25
loss:  3

loss:  18.538537979125977
batch_nr:  205
loss:  19.599334716796875
batch_nr:  206
loss:  12.123735427856445
batch_nr:  207
loss:  10.877176284790039
batch_nr:  208
loss:  25.34575080871582
batch_nr:  209
loss:  12.860795021057129
batch_nr:  210
loss:  20.207881927490234
batch_nr:  211
loss:  22.900226593017578
batch_nr:  212
loss:  20.671958923339844
batch_nr:  213
loss:  26.457462310791016
batch_nr:  214
loss:  20.19486427307129
batch_nr:  215
loss:  6.408452987670898
batch_nr:  216
loss:  17.274702072143555
batch_nr:  217
loss:  21.10826873779297
batch_nr:  218
loss:  19.198881149291992
batch_nr:  219
loss:  18.036794662475586
batch_nr:  220
loss:  20.364213943481445
batch_nr:  221
loss:  25.359813690185547
batch_nr:  222
loss:  13.205558776855469
batch_nr:  223
loss:  17.053560256958008
batch_nr:  224
loss:  6.878844261169434
batch_nr:  225
loss:  12.478123664855957
batch_nr:  226
loss:  15.829628944396973
batch_nr:  227
loss:  21.004255294799805
batch_nr:  228
loss:  20.37257575988

KeyboardInterrupt: 