In [1]:
import torch
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_capability(0))
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))
torch.cuda.set_device(0)
print(torch.cuda.current_device())

AssertionError: 
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

In [11]:
##################  Erstes handmade NN  ####################

import torch
import torch.nn as nn

n_in =10#input
n_h=5 #hidden layer size
n_out=1#output
batch_size=10#batch size
y = torch.tensor([[0.],[1.],[2.],[3.],[4.],[5.]])
x=torch.tensor([[0.],[1.],[2.],[3.],[4.],[5.]])
def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.data.fill_(1.0)
        print(m.weight)
net =nn.Sequential(nn.Linear(1,10),
                   nn.Sigmoid(),
                   nn.Linear(10, 1),
                   )
net.apply(init_weights)
            
criterion = torch.nn.MSELoss()#wie wird loss berechnet            
loss=criterion(y[1],x[0])       

epoch=0
optimizer = torch.optim.SGD(net.parameters(), lr = 0.1)


while loss.item()>0.01:
    epoch+=1
    y_pred = net(x)#model.predict --> ist das selbe in sklearn

    # loss wird anhand von criterion berechnet
    loss = criterion(y_pred, y)
    print("epoch: ",epoch,"Loss: ",loss.item())

    # Gradienten auf null setzen
    optimizer.zero_grad()

    # Backwardpass aller Gewichte und Biases anhand Backpropagation
    loss.backward()

    # Parameterupdate
    optimizer.step()
net(x[2])

Linear(in_features=1, out_features=10, bias=True)
Parameter containing:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)
Sigmoid()
Linear(in_features=10, out_features=1, bias=True)
Parameter containing:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=10, out_features=1, bias=True)
)
epoch:  1 Loss:  31.21257781982422
epoch:  2 Loss:  9.828660011291504
epoch:  3 Loss:  2.1334309577941895
epoch:  4 Loss:  0.9510778188705444
epoch:  5 Loss:  0.6984660029411316
epoch:  6 Loss:  0.6390078067779541
epoch:  7 Loss:  0.6100386381149292
epoch:  8 Loss:  0.5868361592292786
epoch:  9 Loss:  0.5651189088821411
epoch:  10 Loss:  0.5441954731941223
epoch:  11 Loss:  0.5239441990852356
epoch:  12 Loss:  0.5043361783027649
epoch:  13 Loss:  0.4853582382202148

tensor([2.0264], grad_fn=<AddBackward0>)

In [ ]:
########## Convolutional neural net ############

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
import torchvision
from torchvision import datasets,transforms
#für GPU
#device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#
train_loader = torch.utils.data.DataLoader(datasets.MNIST('./data',download=True,train=True,transform=transforms.Compose
                                                          ([transforms.ToTensor()])),batch_size=10,shuffle=True)

test_loader = torch.utils.data.DataLoader(datasets.MNIST('./data',download=True,train=False,transform=transforms.Compose
                                                         ([transforms.ToTensor()])),batch_size=10,shuffle=True)

class MyNet(nn.Module):
    
    def __init__():
        # init weights or layers
    
    def forward():
        raise NotImplementedError 
    

CNN =nn.Sequential(
                   nn.Conv2d(1,32,2),
                   nn.ReLU(),
                   
                   
                   nn.Conv2d(32,128,2),
                   nn.ReLU(),
                   
                   nn.Linear(26,52),
                   nn.ReLU(),
                   
                   nn.Linear(52,104),
                   nn.ReLU(),
    
                   nn.Linear(104,10),
                   nn.ReLU()
                   )
#CNN=CNN.to(device)
criterion = torch.nn.MSELoss()            
def plotter(x,y):
    plt.plot(x,y, label="loss")
    plt.xlabel("iteration*50")
    plt.ylabel("loss")
    plt.pause(0.1)
    
optimizer = torch.optim.Adam(CNN.parameters(),lr=0.25)
def train():
    last_l=0
    last_loss=[]
    
    q=0
    
    lossplot=[]
    for batch_id, (data, label) in enumerate(train_loader):
        last_loss.append(float(last_l))
        data =torch.Tensor(data)
        data=data.float()
        #data=data.to(device)
        target = torch.Tensor(label.float())
        target=target.float()
        #target=target.to(device)
        optimizer.zero_grad()
        preds = CNN(data)
        loss =criterion(preds, target)
        loss.backward()
        last_l=loss.item()
        optimizer.step()
        q+=1
        if q==50:
            lossplot.append(np.mean(last_loss))
           
            q=0
            it=np.arange(0,len(lossplot))
            plotter(it,lossplot)
        
        
train()

9920512it [00:02, 3407708.71it/s]                                                                                      


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz


32768it [00:00, 84288.49it/s]                                                                                          


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz


1654784it [00:01, 1298673.53it/s]                                                                                      


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz


8192it [00:00, 31895.40it/s]                                                                                           


Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz
Processing...
Done!


c:\users\max\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\loss.py:443: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([10, 128, 26, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>